<div class="p-fSlider">
      <ul class="p-fSlider__body">
        <li class="p-fSlider__item">
          <a class="p-fSlider__link" href="http://www.metro.tokyo.jp/" target="_blank">
           　
            　<img src="/images/f_slider_img_01.png" width="225" height="60" alt="東京都" />
        </a>
        </li>
        <li class="p-fSlider__item">
          <a class="p-fSlider__link" href="http://www.sangyo-rodo.metro.tokyo.jp/" target="_blank">
           　
            　<img src="/images/f_slider_img_02.png" width="225" height="60" alt="東京都産業労働局" />
        </a>
        </li>
      </ul>
      <!-- /.p-fSlider__body -->
    </div>
    <!-- /.p-fSlider -->
