<section class="p-topContents__bottom">
          <div class="p-pickup">
            <div class="p-pickup__body">
              <h2 class="p-sectionTtl"><img src="/images/section_ttl_pickup__pc.png" width="182" height="53"
                  alt="PICK UP" /></h2>
              <div class="p-pickupContent">
                <div class="p-pickupContent__item">
                  <a class="p-pickupCard" href="/torikumi/482/">
                    <p class="p-pickupCard__date">2023.08.07</p>
                    <p class="p-pickupCard__ttl">「令和5年度中小企業サイバーセキュリティ向上支援事業」参加企業の募集</p>
                    <p class="p-pickupCard__txt">東京都事業「令和5年度中小企業サイバーセキュリティ向上支援事業」の参加企業の募集に関するページです。</p>
                    <p class="p-pickupCard__more"><span>詳細をチェック</span></p>
                  </a>
                </div>
                <div class="p-pickupContent__item">
                  <a class="p-pickupCard" href="/torikumi/478/">
                    <p class="p-pickupCard__date">2023.05.31</p>
                    <p class="p-pickupCard__ttl">「令和５年度中小企業サイバーセキュリティ対策強化サポート事業」参加企業の募集開始</p>
                    <p class="p-pickupCard__txt">東京都事業「令和５年度中小企業サイバーセキュリティ対策強化サポート事業」の参加企業の募集に関するページです</p>
                    <p class="p-pickupCard__more"><span>詳細をチェック</span></p>
                  </a>
                </div>
                <div class="p-pickupContent__item">
                  <a class="p-pickupCard" href="/torikumi/476/">
                    <p class="p-pickupCard__date">2023.05.18</p>
                    <p class="p-pickupCard__ttl">「令和5年度中小企業サイバーセキュリティ対策継続支援事業」参加企業の募集開始</p>
                    <p class="p-pickupCard__txt">東京都事業「令和5年度中小企業サイバーセキュリティ対策継続支援事業」の参加企業の募集に関するページです。</p>
                    <p class="p-pickupCard__more"><span>詳細をチェック</span></p>
                  </a>
                </div>
                <div class="p-pickupContent__item">
                  <a class="p-pickupCard" href="/torikumi/474/">
                    <p class="p-pickupCard__date">2023.05.12</p>
                    <p class="p-pickupCard__ttl">令和５年度「サイバーセキュリティ対策促進助成金」募集のお知らせ</p>
                    <p class="p-pickupCard__txt">（公財）東京都中小企業振興公社（以下、「公社」）は、都内中小企業等が自社の企業秘密や個人情報等を保護する観点から構築したサイバーセキュリティ対策を実施するための設備等の導入に要する経費への助成を行っています。</p>
                    <p class="p-pickupCard__more"><span>詳細をチェック</span></p>
                  </a>
                </div>
                <div class="p-pickupContent__item">
                  <a class="p-pickupCard" href="/security/guidebook/">
                    <p class="p-pickupCard__date">2022.05.20</p>
                    <p class="p-pickupCard__ttl">ガイドブック「中小企業向けサイバーセキュリティ対策の極意」Ver2.2を公開しました。</p>
                    <p class="p-pickupCard__txt">PDF版をVer2.2に、EPUB版をVer2.2.1にして公開しました。引き続き順次公開していきます。</p>
                    <p class="p-pickupCard__more"><span>詳細をチェック</span></p>
                  </a>
                </div>
                <div class="p-pickupContent__item">
                  <a class="p-pickupCard" href="/security/cyberthreat/403/index.html">
                    <p class="p-pickupCard__date">2022.02.28</p>
                    <p class="p-pickupCard__ttl">【経済産業省】昨今の情勢を踏まえたサイバーセキュリティ対策の強化について注意喚起を行います</p>
                    <p class="p-pickupCard__txt">【経済産業省】「昨今の情勢を踏まえたサイバーセキュリティ対策の強化について注意喚起を行います」に関するページです。</p>
                    <p class="p-pickupCard__more"><span>詳細をチェック</span></p>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
